### ISSUE TITLE
Stopping and starting the animation produces a flicker.

### ISSUE THREAD

**Issue by blalc** [CatalystApps/Cocos2dxGAFPlayer#53]
Whenever I play an animation (say animation A) and then stop it midway (say on frame x of animation A), and after that play another animation (say animation B), on the start of animation B there is a noticeable flicker of frame x on screen. I am using cocos2d-x 3.3. I stop animations midway and then hide them as I do not want it to complete. Later when I play the animation the last frame of previous animation on which the previous animation was stopped flickers on screen.

**Comment by SmartCat** [comment]
Hello!
Could you please provide more info?
I've changed GafFeatures class in Examples to test this issue.
I stop and hide animation A on frame 200. On click I start animation B.
It seems that I missed some condition - no flickers.
https://drive.google.com/file/d/0ByYIXG-tjt6AdlZzdC1ER21GRDA/view?usp=sharing

**Comment by blalc** [comment]
Hi,

I've more than one animation in a single GAF file.

**Scenario 1:**
I play one animation in that file and stop it midway and hide it. Then I again play the same animation in the same GAF file and show it. The frame on which this animation was stopped is visible in a flicker before that animation starts fresh.

**Scenario 2:**
I play one animation in that file and stop it midway and hide it. Then I play another animation in the same GAF file and show it. The frame on which the first animation was stopped is visible in a flicker before the second animation starts fresh.

**Modified GafFeatures Class in Examples**
This is also reproducible with a GAF file with only one animation in it, like those in _Examples_. I've also changed GafFeatures class in _Examples_ to better explain this issue. I stop and hide a running animation on pause button callback, and I start and show the same animation on play button callback. Note that for animations that do not move around the screen the issue is hard to notice unless watching very closely. But, if you go to the lion and cub animation included in _Examples_ and press pause(which stops and hides the animation) button when the cub is away from lion, and then press play(which starts and shows the animation) you'll be able to see the frame on which the animation was stopped in a flicker before the lion and cub animation starts fresh.
_Link to the modified GafFeatures class_
https://drive.google.com/folderview?id=0B8XTo1j-Gqt2OGlEaDdZNHJDN28&usp=sharing

**Comment by SmartCat** [comment]
Hello, this was fixed in 
https://github.com/CatalystApps/Cocos2dxGAFPlayer/commit/61a0925e28799efd5e1e6e4394cf4636af78e3b4

**Comment by abdulwasay** [comment]
@SmartCat 
This is still easily reproducible on the release-gaf-5 branch. I have looked at the code and the changes made in the commit mentioned above are still present. I think the code changes do not fix the issue.

Steps to reproduce.
1. Replace the playpause function in GafFeatures.cpp with the following function

``` code
void GafFeatures::playpause(cocos2d::Ref*)
{
    if (!m_objects || !m_objects->count())
    {
        return;
    }

    GAFObject *object = (GAFObject *)m_objects->getObjectAtIndex(0);

    if (object->getIsAnimationRunning())
    {
        object->stop();
        object->setVisible(false);
    }
    else
    {
        object->start();
        object->setVisible(true);
    }
}
```
1. Scroll to the peacock animation
2. Let the peacock move to the left of the screen and open its feathers
3. Press play / pause button
4. Press play / pause button again
5. Notice that there is a flicker of the peacock with open feathers before the animation begins from the original location

**Comment by abdulwasay** [comment]
@SmartCat 

``` code
object->setFrame(0); 
```

after stopping the animation solves the issue for me.

Maybe I misunderstood how stop and start is supposed to work?

**Comment by SmartCat** [comment]
Hi!
I've commit small fix for your issue. 
Thank you

P.S. https://github.com/CatalystApps/Cocos2dxGAFPlayer/commit/3529e1b95cc5aaa79b12a243fd4106803d982fe8

**Comment by abdulwasay** [comment]
@SmartCat 
Thank You.
I found the same issue in the playSequence method in GAFObject.cpp

Perhaps changing the following line from

``` code
m_currentFrame = m_isReversed ? (e - 1) : (s);
```

to

``` code
m_currentFrame = m_isReversed ? (e - 1) : (s);
setFrame(m_currentFrame);
```

would fix this as well.

**Comment by SmartCat** [comment]
Fixed also,
Thanks

**Comment by abdulwasay** [comment]
Thank You :)
